### ISSUE TITLE
Long term: add ability to ask Area Detectors if they are done writing data.

### ISSUE THREAD

**Issue by danielballan** [danielballan/bluesky#23]
Delay RunStop until all detectors are done. Therefore, all data should be available to validate and we ensure that we don't start a new run and screw up filenames.

For now, act under the assumption that when RunStop is written detector is about done so we can start validating its data in chronological order.

**Comment by tacaswell** [comment]
There is a pr in to ophyd to block de configure until all data is written to disk, closing as needs upstream fix.
