### ISSUE TITLE
start up checklist

### ISSUE THREAD

**Issue by tacaswell** [danielballan/bluesky#77]
Make one of the startup files explicitly check all of the connectivity at IPython start time, ex check olog, mds, fs, ...

**Comment by danielballan** [comment]
Stuff to check:

* Can we see the MDS mongo?
* Can we see the FS mongo?
* Can we talk to Olog?
* Is the ChannelArchiver alive?
* Can we see the storage where FS is aimed? Bluesky/ophyd does not actually *need* to see it, but it often can. If it can, is there sufficient hard drive space.
* Do {insert PV here} have value {insert value here}?

Functions to check all of this can be added to bluesky/standard_config.py. Then, in the IPython startup, we can curry them using partials to be a set of argument-less functions, in turn called by one "checklist" function.

*Then* all this should be wrapped in a continually-running loop (probably a second event loop) that can panic the RunEngine if the checklist reports a problem.

**Comment by tacaswell** [comment]
Closed by #136
