### ISSUE TITLE
Regarding table formatting

### ISSUE THREAD

**Issue by ericdill** [danielballan/bluesky#95]
It would be interesting to deal with numeric formatting by setting an attribute on the Epics object. 

Something like `theta.numeric_format = '000.000'` will always format theta with three numbers before and three numbers after the decimal.  And sclr.numeric_format = 'int' will always format sclr as an integer.  These are parameters that need to be decided by the beamline scientists, but this would make formatting the numbers super easy.

**Comment by danielballan** [comment]
So, this is an ophyd/pyepics issue. Pull more datatype info from epics and put a `format_string` field in the Event Descriptor, probably in the data keys. See NSLS-II/ophyd#135
